### ISSUE TITLE
[FE] 메인화면 ToDo

### ISSUE THREAD

**Issue by junzero741** [kjk402/airbnb#2]
## 헤더 정적 UI
   - [x] 호버 효과만 있는 버튼들 추가 ( 19. 수 )
## 검색창 UI
   - [x]  검색창 정적 UI ( 19. 수 )
   - [x]  모달 닫기 및 스위칭 기능 구현 (21. 금)
   - [x]  인원 조정 모달 (20. 목)
        -  모달 팝업
        -  인원 추가 로직 구현
        -  선택한 인원 검색바 반영
        -  인원 선택 초기화 기능
   - [x]  캘린더 모달 (21. 금 ~ 27. 목)
       - 모달 팝업 
       - 슬라이드 기능
       - 날짜 선택 로직 구현
       - 선택한 날짜 검색창 반영
       - 날짜 선택 초기화 기능
   - [x]  요금 모달
       - 모달 팝업 
       - 레인지 슬라이더 기능
       - 가격범위 텍스트 및 검색바와 슬라이더 동기화
       - 숙소 개수와 가격에 따른 범위 내 그래프 렌더링
       - 값 선택 초기화 기능
    - [ ] 지역 검색 모달
       - 모달 없이 입력만 받아서 검색 필터 state 에 반영되도록 구현
