### ISSUE TITLE
[FE] 검색결과 ToDo

### ISSUE THREAD

**Issue by junzero741** [kjk402/airbnb#3]
## 헤더
- [x] 미니 검색 바의 placeholder에는 메인 페이지에서 검색한 내용으로 채워짐
- [x] 미니 검색 바 클릭하면 메인 페이지와 동일한 큰 검색바 노출

## 숙소리스트
- [x] 메인 페이지 혹은 검색결과 페이지에서 검색한 내용 상단에 노출
- [x] 서버로부터 숙소리스트 fetch
- [x] 숙소 클릭시 예약 모달창 팝업
  - [ ]  체크인/체크아웃 혹은 인원 영역 클릭하면 메인 페이지에서 떴던 모달 팝업 
  - [x]  모달 창 닫기 기능
  

## 지도
- [x] 지도 API 활용
- [ ] 지도 움직이며 검색하는 기능 on/off 버튼
- [x] 지도 확대 축소 버튼
